# Generated by Django 6.0.6 on 2026-07-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='days',
            field=models.IntegerField(default=1),
        ),
    ]
