# Generated by Django 6.0.6 on 2026-07-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_trip_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='members',
            field=models.IntegerField(default=1),
        ),
    ]
