# Generated by Django 6.0.6 on 2026-07-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_trip_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('hotel', models.CharField(max_length=100)),
                ('restaurant', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('police', models.CharField(max_length=100)),
                ('bus_stand', models.CharField(max_length=100)),
                ('railway_station', models.CharField(max_length=100)),
            ],
        ),
    ]
