# Generated by Django 6.0.6 on 2026-07-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('ambulance', models.CharField(max_length=20)),
                ('police', models.CharField(max_length=20)),
                ('fire', models.CharField(max_length=20)),
                ('helpline', models.CharField(max_length=20)),
            ],
        ),
    ]
