# Generated by Django 6.0.6 on 2026-07-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_emergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('best_time', models.CharField(max_length=100)),
                ('transport', models.CharField(max_length=100)),
                ('tip', models.TextField()),
            ],
        ),
    ]
