# Generated by Django 6.0.6 on 2026-07-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planned', max_length=20),
        ),
    ]
