# Generated by Django 6.0.6 on 2026-07-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_trip_end_date_trip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='spent_amount',
            field=models.IntegerField(default=0),
        ),
    ]
